catalog/urls.py
from django.urls import path
from . import views
from .views import IndexPage, ProductsPage, PurchaseView, AboutPage, ContactPage, ProductCategoryPage

app_name = 'shop'

urlpatterns = [
    path('', IndexPage.as_view(), name='home'),
    path('products/', ProductsPage.as_view(), name='products'),
    path('about_us/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('products/<str:category>/', ProductCategoryPage.as_view(), name='products_category'),
    path('purchase/<int:product_id>/', PurchaseView.as_view(), name='purchase'),
]

    

manager/urls.py
from django.urls import path
from .views import ManagerIndex, EditPurchases

app_name = 'manager'

urlpatterns = [
    path('', ManagerIndex.as_view(), name='index'),
    path('purchases/<int:pk>/', EditPurchases.as_view(), name='edit_purchases'),
]

my_internet_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_internet_shop import settings
from account.views import RegisterUser, LoginUser, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('manager/',include('manager.urls')),
    
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/banner.html
<!-- Banner Starts Here -->
<div class="banner header-text">
    <div class="owl-banner owl-carousel">
      <div class="banner-item-01">
        <div class="text-content">
          <h4>Best Offer</h4>
          <h2>New Arrivals On Sale</h2>
        </div>
      </div>
      <div class="banner-item-02">
        <div class="text-content">
          <h4>Flash Deals</h4>
          <h2>Get your best products</h2>
        </div>
      </div>
      <div class="banner-item-03">
        <div class="text-content">
          <h4>Last Minute</h4>
          <h2>Grab last minute deals</h2>
        </div>
      </div>
    </div>
  </div>
  <!-- Banner Ends Here -->

templates/includes/footer.html
<!--Footer--> 
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="inner-content">
            <p>Copyright &copy; 2020 Sixteen Clothing Co., Ltd.
          
          - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
<!--End Footer-->

templates/includes/navbar.html
<nav id="navbar" class="navbar">
  <ul class="navbar-nav justify-content-end">
    {% for item in catalog_item %}
      <li class="nav-item">
        <a class="nav-link" href="{% if item.is_anchor %}{{ item.get_absolute_url }}{% else %}{% url "shop:products" %}{% endif %}">{{ item.title }}</a>
      </li>
    {% endfor %}

    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'registration' %}">Sign up</a>
      </li>
    {% endif %}

        {% if user.groups.exists and user.groups.first.name == 'manager' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'manager:index' %}">Manager</a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/includes/reviews.html
<!--Reviews-->
<div class="latest-products">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-heading">
          <h2>Latest Products</h2>
          <a href= {% url "shop:products"%}>view all products <i class="fa fa-angle-right"></i></a>
        </div>
      </div>
      <div class="latest-products">
        <div class="container">
          <div class="row">
            {% for product in products %}
              <div class="col-md-4">
                <div class="product-item">
                  <a href="#"><img src="{{ product.photo.url }}" alt="{{ product.title }}"></a>
                  <div class="down-content">
                    <a href="#"><h4>{{ product.title }}</h4></a>
                    <h6>${{ product.price }}</h6>
                    <p>{{ product.description }}</p>
                    <!-- Додайте код для виведення рейтингу, відгуків тощо. -->
                  </div>
                </div>
              </div>
            {%endfor%}
        </div>
      </div>