catalog/urls.py
from django.urls import path
from . import views
from .views import IndexPage, ProductsPage, PurchaseView, AboutPage, ContactPage, ProductCategoryPage

app_name = 'shop'

urlpatterns = [
    path('', IndexPage.as_view(), name='home'),
    path('products/', ProductsPage.as_view(), name='products'),
    path('about_us/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('products/<str:category>/', ProductCategoryPage.as_view(), name='products_category'),
    path('purchase/<int:product_id>/', PurchaseView.as_view(), name='purchase'),
]

    

manager/urls.py
from django.urls import path
from .views import ManagerIndex, EditPurchases

app_name = 'manager'

urlpatterns = [
    path('', ManagerIndex.as_view(), name='index'),
    path('purchases/<int:pk>/', EditPurchases.as_view(), name='edit_purchases'),
]

my_internet_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_internet_shop import settings
from account.views import RegisterUser, LoginUser, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('manager/',include('manager.urls')),
    
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from catalog.models import Order


class PurchasesEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'email', 'address', 'is_precessed')

manager/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, UpdateView
from catalog.models import Order
from django.urls import reverse_lazy, reverse
from .forms import PurchasesEditForm


class ManagerAccessMixin(UserPassesTestMixin):

    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists()
    
    
class ManagerIndex(LoginRequiredMixin,ManagerAccessMixin , ListView):
    template_name = 'manager_index.html'
    login_url = '/login/'
    model = Order
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(is_precessed= False)


class EditPurchases(LoginRequiredMixin, ManagerAccessMixin, UpdateView):
    template_name = 'edit_purchases.html'
    login_url = '/login/'
    model = Order
    form_class = PurchasesEditForm
    success_url = reverse_lazy('manager:index')

manager/templates/edit_purchases.html
{% extends 'index.html' %}

{% block content %}
    <div class="container mt-5">
        <h1></h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <a href="{% url 'manager:index' %}" class="btn btn-secondary mt-3">To Shopping</a>
    </div>
{% endblock %}

manager/templates/manager_index.html
{% extends 'index.html' %}

{% block content %}
    <div class="container mt-5">
        <h1>Shop List</h1>
        <div class="list-group mt-4">
            {% for order in orders%}
                <div class="list-group-item">
                    <h5 class="mb-1">Name : {{ order.name }}</h5>
                    <p class="mb-1">E-Mail : {{ order.email }}</p>
                    <p class="mb-1">Adress : {{ order.address }}</p>
                    <a href="{% url 'manager:edit_purchases' order.id %}" class="btn btn-primary btn-sm float-right">Confirm</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}