catalog/urls.py
from django.urls import path
from . import views
from .views import IndexPage, ProductsPage, PurchaseView, AboutPage, ContactPage, ProductCategoryPage

app_name = 'shop'

urlpatterns = [
    path('', IndexPage.as_view(), name='home'),
    path('products/', ProductsPage.as_view(), name='products'),
    path('about_us/', AboutPage.as_view(), name='about'),
    path('contact/', ContactPage.as_view(), name='contact'),
    path('products/<str:category>/', ProductCategoryPage.as_view(), name='products_category'),
    path('purchase/<int:product_id>/', PurchaseView.as_view(), name='purchase'),
]

    

my_internet_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_internet_shop import settings
from account.views import RegisterUser, LoginUser, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('manager/',include('manager.urls')),
    
    path('registration/', RegisterUser.as_view(), name='registration'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Sixteen Clothing - About Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel= 'stylesheet' href= {% static 'assets/css/fontawesome.css'%}>
    <link rel= 'stylesheet' href= {% static 'assets/css/templatemo-sixteen.css'%}>
    <link rel= 'stylesheet' href= {% static 'assets/css/owl.css'%}>
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

   <!-- Header -->
   <header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        {% include 'includes/navbar.html' %}
        <a class="navbar-brand" href={% url "shop:home" %}><h2>Sixteen <em>Clothing</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
          aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% for item in catalog_items %}
            <li class="nav-item {% if request.path == item.get_absolute_url %}active{% endif %}">
              <a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
    {% include "page_content.html"%}

    <!-- Bootstrap core JavaScript -->
    <script src={% static 'vendor/jquery/jquery.min.js'%}></script>
    <script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}></script>


    <!-- Additional Scripts -->
    <script src={% static 'assets/js/custom.js'%}></script>
    <script src={% static 'assets/js/owl.js'%}></script>
    <script src={% static 'assets/js/slick.js'%}></script>
    <script src={% static 'assets/js/isotope.js'%}></script>
    <script src={% static 'assets/js/accordions.js'%}></script>
    
    
    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

templates/contact.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Sixteen Clothing - Contact Page</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'vendor/bootstrap/css/bootstrap.min.css'%} rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel= 'stylesheet' href={% static "assets/css/fontawesome.css"%}>
    <link rel= 'stylesheet' href={% static "assets/css/templatemo-sixteen.css"%}>
    <link rel= 'stylesheet' href={% static "assets/css/owl.css"%}>

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
<!-- Header -->
<header class="">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      {% include 'includes/navbar.html' %}
      <a class="navbar-brand" href={% url "shop:home" %}><h2>Sixteen <em>Clothing</em></h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% for item in catalog_items %}
          <li class="nav-item {% if request.path == item.get_absolute_url %}active{% endif %}">
            <a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.title }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>
</header>
          
  
    {%include "page_content_contact.html"%}

    <!-- Bootstrap core JavaScript -->
    <script src={% static 'vendor/jquery/jquery.min.js'%}></script>
    <script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}></script>


    <!-- Additional Scripts -->
    <script src={% static 'assets/js/custom.js'%}></script>
    <script src={% static 'assets/js/owl.js'%}></script>
    <script src={% static 'assets/js/slick.js'%}></script>
    <script src={% static 'assets/js/isotope.js'%}></script>
    <script src={% static 'assets/js/accordions.js'%}></script>


  </body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap"
    rel="stylesheet">

  <title>Sixteen Clothing HTML Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

  <!-- Additional CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/css/templatemo-sixteen.css' %}">
  <link rel="stylesheet" href={% static 'assets/css/fontawesome.css' %}>
  <link rel="stylesheet" href={% static 'assets/css/owl.css' %}>
</head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="preloader">
    <div class="jumper">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->
  <!-- Header -->
  <header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        {% include 'includes/navbar.html' %}
        <a class="navbar-brand" href={% url "shop:home" %}><h2>Sixteen <em>Clothing</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
          aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% for item in catalog_items %}
            <li class="nav-item {% if request.path == item.get_absolute_url %}active{% endif %}">
              <a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- Page Content -->

  <!-- Banner Starts Here -->
  {% include "includes/banner.html" %}

  {% block content %}
  {% endblock %}

  <!-- Reviews -->
  {% include "includes/reviews.html" %}
  <!-- End Reviews-->
  
  <!--Footer-->
  {% include "includes/footer.html" %}
  <!--End Footer-->

  <!-- Bootstrap core JavaScript -->
  <script src={% static 'vendor/jquery/jquery.min.js' %}></script>
  <script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}></script>

  <!-- Additional Scripts -->
  <script src={% static 'assets/js/custom.js' %}></script>
  <script src={% static 'assets/js/owl.js' %}></script>
  <script src={% static 'assets/js/slick.js' %}></script>
  <script src={% static 'assets/js/isotope.js' %}></script>
  <script src="{% static 'assets/js/accordions.js' %}"></script>




</body>

</html>

templates/products.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Sixteen Clothing Products</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
  

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

     <!-- Header -->
     <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          {% include 'includes/navbar.html' %}
          <a class="navbar-brand" href={% url "shop:home" %}><h2>Sixteen <em>Clothing</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              {% for item in catalog_items %}
              <li class="nav-item {% if request.path == item.get_absolute_url %}active{% endif %}">
                <a class="nav-link" href="{{ item.get_absolute_url }}">{{ item.title }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
<!-- Page Content -->
{% include "page_content_products.html" %}



<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'assets/js/custom.js' %}"></script>
<script src="{% static 'assets/js/owl.js' %}"></script>
<script src="{% static 'assets/js/slick.js' %}"></script>
<script src="{% static 'assets/js/isotope.js' %}"></script>
<script src="{% static 'assets/js/accordions.js' %}"></script>
  </body>

</html>